# Generated by Django 4.2.1 on 2024-03-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='associated_hab',
            new_name='associated_habit',
        ),
    ]
